    CREATE DATABASE DBEXERCICIOO003;

    USE DBEXERCICIOO003;

    CREATE TABLE USARIO (
        IDUSUARIO INT NOT NULL AUTO_INCREMENT
        ,EMAIL VARCHAR(120) NOT NULL
        , PAIS VARCHAR(50)
        , PRIMARY KEY (IDUSUARIO) 

    );

